import numpy as np
from .utils.mpi import mpi_watch, is_master, comm
from .utils.misc import simple_timer, index_traverse
from .matao.findpairs import pairs_within_cutoff
from .matao.matao import MatAO
from .io.aodata import AOData
from .io.struio import load_structure, from_qexml, from_bgw, from_poscar, from_gpaw
from .io.deephio import save_structure_deeph, save_mat_deeph, load_mat_deeph, analyze_hdecay_deeph
from .io.siestaio import get_hs_siesta
from .io.hrloader import read_vnloc, read_vloc
from .pw.wfndata import WFNData
from .pw.hgdata import HGData, HGDataPAW
from .pwproj import Hpw_to_Hao_wfn, Hpw_to_Hao_HG, wfn_proj_to_atoms
from .v2h.vkb import calc_vkb, get_nloc_pairs
from .v2h.twocenter import calc_overlap
from .v2h.gridintg import GridIntgWorker


class PW2AOkernel:
    
    @mpi_watch
    @simple_timer('IO done, total wall time = {t}')
    def __init__(self, 
                 aodata_interface=None, aodata_root=None, spinful=False, magnetic=False,
                 wfn_interface=None, wfndata_root=None, wfn_max_band=None, 
                 hgdata_interface=None, hrdata_interface=None,
                 vscdir=None, vkbdir=None, 
                 gpawsave=None, gpaw_datadir=None, upfdir=None,
                 structure_interface=None, structure_path=None,
                 overlaps_only=False,
                 kgrid=None, ecutwfn=None):
        '''
        Parameters:
        ---------

        aodata_interface:     Currently supports 'siesta' and 'gpaw'. AO data is the information for atomic orbital basis.
        aodata_root:          If aodata_interface='siesta', then this should be folder containing x.ion where x is the atomic symbol.
                              If aodata_interface='gpaw', then this should contain x.(...).basis, where x is the atomic symbol, and 
                              the contents in the bracket is optional.
        
        wfn_interface:        Currently supports 'qe' or 'bgw'.
        wfndata_root:         If wfn_interface='qe': the folder containing data-file-schema.xml and wfc*.hdf5
                              If wfn_interface='bgw': the BGW WFN file
        wfn_max_band:         Specify maximum number of bands to read file disk faster. This wfn_max_band is 1-based index. 
        
        hgdata_interface:     Currently supports 'bgw'and 'gpaw'. HGData is the information for the Hamiltonian under plane-wave
                              basis. ecutwfn will not be needed here because the energy cutoff will be read from input data.

            If hgdata_interface='bgw':   you should specify vscdir and vkbdir.
            If hgdata_interface='gpaw':  you should specify gpawsave which is the binary xxx.gpw file generated by a gpaw run, and 
                                         gpaw_datadir which contains the GPAW pseudopotential x.PBE(.gz) where x is the atomic symbol, 
                                         and .gz is optional.
        
        hrdata_interface:     Currently supports 'qe-bgw' and 'gpaw'. HrData is the information for the Hamiltonian in real space.
                              ecutwfn will be needed.

            If hrdata_interface='qe-bgw':   you should specify vscdir and upfdir, where upfdir is the folder containing the QE
                                         pseudopotential file x.upf.
            If hrdata_interface='qe-siesta':   you should specify vscdir, and aodata_root which contains the siesta .ion files.
            If hrdata_interface='gpaw':  you should specify gpawsave which is the binary xxx.gpw file generated by a gpaw run, and 
                                         gpaw_datadir which contains the GPAW pseudopotential x.PBE(.gz) where x is the atomic symbol, 
                                         and .gz is optional.
            If hrdata_interface='qe-deephr: you should specify vscdir (Vtot.h5) and upfdir, where upfdir is the folder containing the QE
                                         pseudopotential file x.upf. You should also provide structure information separately.

        overlaps_only:        If this is True, only the overlap will be calculated but not the Hamiltonian. The user must also provide 
                              hrdata_interface and corresponding data. 

            If hrdata_interface='qe-bgw':   only upfdir is needed, where upfdir is the folder containing the QE
                                         pseudopotential file x.upf.
            If hrdata_interface='qe-deephr': same as 'qe-bgw'.
            If hrdata_interface='gpaw':  Only gpaw_datadir is needed, which contains the GPAW pseudopotential x.PBE(.gz) where 
                                         x is the atomic symbol, and .gz is optional.
        
        structure_interface:  Usually, the structure information can be automatically determined if hgdata or hrdata is provided. However,
                              if neither of these are provided, or using overlaps_only, then you should specify an additional way for the
                              code to determine the material structure. Currently supports 'qe', 'bgw', 'vasp', 'gpaw', 'deeph'.
        structure_path:       If structure_interface='qe': the folder containing data-file-schema.xml
                              If structure_interface='bgw': could be WFN, VSC, VKB
                              If structure_interface='vasp': the POSCAR file
                              If structure_interface='gpaw': the binary xxx.gpw file
                              If structrue_interface='deeph': the folder containing lat.dat, site_positions.dat, element.dat, info.json
        

        kgrid:          use None to read k-grid and k-weights from input data (qe-xml or bgw binary header); 
                        or specify a grid (e.g. [3, 3, 1]) to overwrite the original k-grid.
        '''
        
        if is_master():
            print()
            print('==============================================================================')
            print('Program HPRO')
            print('Author: Xiaoxun Gong (xiaoxun.gong@gmail.com)')
            print('==============================================================================')
            print()
        
        if comm is not None:
            if comm.rank == 0:
                print('Using MPI')
                print(f'Number of processors: {comm.size}')
                print()
        else:
            print('Module mpi4py not found, execucting serially\n')
            
        if aodata_interface is not None:
            aodata_interface = aodata_interface.lower()
        if wfn_interface is not None:
            wfn_interface = wfn_interface.lower()
        
        # determine structure, and check corresopnding input
        structure = None
        def check_structure(structure, stru1):
            if structure is None:
                structure = stru1
            elif structure != stru1:
                raise ValueError('Structure mismatch')
            return structure
        if wfn_interface is not None:
            assert wfndata_root is not None
            if wfn_interface == 'qe':
                stru1 = from_qexml(f'{wfndata_root}/data-file-schema.xml')
            elif wfn_interface == 'bgw':
                stru1 = from_bgw(f'{wfndata_root}')
            else:
                raise NotImplementedError(f'Unknown wfn_interface {wfn_interface}')
            structure = check_structure(structure, stru1)
        if hgdata_interface is not None:
            if hgdata_interface == 'bgw':
                assert vscdir is not None
                stru1 = from_bgw(vscdir)
            elif hgdata_interface == 'gpaw':
                assert gpawsave is not None
                stru1 = from_gpaw(gpawsave)
            else:
                raise NotImplementedError(f'Unknown hgdata_interface {hgdata_interface}')
            structure = check_structure(structure, stru1)
        if hrdata_interface is not None and not overlaps_only:
            if hrdata_interface == 'qe-bgw':
                assert vscdir is not None
                stru1 = from_bgw(vscdir)
            elif hrdata_interface == 'qe-deephr':
                assert vscdir is not None
                stru1 = None # later we read xml file to determine structure
            elif hrdata_interface == 'gpaw':
                assert gpawsave is not None
                stru1 = from_gpaw(gpawsave)
            else:
                raise NotImplementedError(f'Unknown hrdata_interface {hrdata_interface}')
            structure = check_structure(structure, stru1)
        if structure_interface is not None:
            assert structure_path is not None
            stru1 = load_structure(structure_path, structure_interface)
            structure = check_structure(structure, stru1)
        
        assert structure is not None, 'Must provide structure information'
        if is_master():
            structure.echo_info()
            print()
        
        # spinful and magnetism
        self.spinful = spinful
        self.magnetic = magnetic
        self.aomats_dtype = 'f8' if not self.spinful else 'c16'
        if self.spinful and is_master():
            print('Spinful calculation enabled\n')
        if self.magnetic:
            raise NotImplementedError("Magnetic calculations are not supported yet.")
        if spinful or magnetic:
            if wfn_interface is not None:
                raise NotImplementedError("Wavefunctions from spinful/magnetic calculations are not supported yet.")
            if hgdata_interface is not None:
                raise NotImplementedError("hgdata H(G) from spinful/magnetic calculations are not supported yet.")
            if (hrdata_interface is not None) and (hrdata_interface not in ['qe-bgw', 'qe-deephr']):
                raise NotImplementedError(f"hrdata_interface '{hrdata_interface}' does not support spinful/magnetic calculations.")

        # get aodata
        if aodata_interface is not None:
            assert structure is not None, 'Must provide structure information for lcao data to be initialized'
            aodata = AOData(structure, basis_path_root=aodata_root, aocode=aodata_interface)
            aodata.check_rstart()
        else:
            raise NotImplementedError()

        if is_master():
            print('Atomic orbital basis:')
            aodata.echo_info()
            print()
        
        # get wfndata
        if wfn_interface is not None:
            wfndata = WFNData(structure, wfn_path_root=wfndata_root, pwcode=wfn_interface, kgrid=kgrid, maxband=wfn_max_band, 
                              )
        else:
            wfndata = None
        
        # get hgdata
        if hgdata_interface == 'bgw':
            assert vscdir is not None and vkbdir is not None
            hgdata = HGData(vscfile=vscdir, vkbfile=vkbdir, structure=structure, kgrid=kgrid, interface='bgw')
        elif hgdata_interface == 'gpaw':
            assert gpawsave is not None and gpaw_datadir is not None and ecutwfn is not None
            hgdata = HGDataPAW(gpawsave=gpawsave, gpaw_datadir=gpaw_datadir, structure=structure, kgrid=kgrid, ecutwfn=ecutwfn, interface='gpaw')
        elif hgdata_interface is not None:
            raise NotImplementedError(hgdata_interface)
        else:
            hgdata = None
        
        # get hrdata
        if hrdata_interface is not None:
            if not overlaps_only:
                if (hrdata_interface == 'qe-bgw') or (hrdata_interface == 'qe-deephr'):
                    assert vscdir is not None and upfdir is not None
                    vlocr = read_vloc(vscdir, hrdata_interface.split('-')[1]) # bgw or deephr
                    Dij, Qij, projR = read_vnloc(structure, upfdir, interface='qe')
                    if np.isrealobj(Dij) != (not self.spinful):
                        raise ValueError('Pseudopotential type mismatch with input spinful option')
                elif hrdata_interface == 'qe-siesta':
                    assert vscdir is not None
                    vlocr = read_vloc(vscdir, hrdata_interface.split('-')[1]) # bgw or deephr
                    Dij, Qij, projR = read_vnloc(structure, aodata_root, interface='siesta')
                elif hrdata_interface == 'gpaw':
                    assert gpawsave and gpaw_datadir is not None
                    vlocr = read_vloc(gpawsave, 'gpaw')
                    Dij, Qij, projR = read_vnloc(structure, gpaw_datadir, dijfile=gpawsave, interface='gpaw')
                else:
                    raise NotImplementedError(f'Unknown hrdata_interface {hrdata_interface}')
            else:
                vlocr = None
                if (hrdata_interface == 'qe-bgw') or (hrdata_interface == 'qe-deephr'):
                    assert upfdir is not None
                    Dij, Qij, projR = read_vnloc(structure, upfdir, interface='qe')
                elif hrdata_interface == 'qe-siesta':
                    Dij, Qij, projR = read_vnloc(structure, aodata_root, interface='siesta')
                elif hrdata_interface == 'gpaw':
                    assert gpaw_datadir is not None
                    Dij, Qij, projR = read_vnloc(structure, gpaw_datadir, dijfile=None, interface='gpaw')
                else:
                    raise NotImplementedError(f'Unknown hrdata_interface {hrdata_interface}')
            hrdata = (vlocr, Dij, Qij, projR)
            if is_master():
                if vlocr is not None:
                    print('Real space grid dimensions: (' + ' '.join(f'{vlocr.shape[i]:5d}' for i in range(3)) + ')\n')
                print('Pseudopotential projectors:')
                projR.echo_info()
                print()
        else:
            hrdata = None

        self.structure = structure
        self.aodata = aodata
        self.wfndata = wfndata
        self.hgdata = hgdata
        self.ecutwfn = ecutwfn #! from file?
        self.hrdata = hrdata
        self.overlaps_only = overlaps_only
    
    @mpi_watch
    @simple_timer('\nJob done, total wall time = {t}\n')
    def run_pw2ao(self, savedir, cutoffs=None, nbndmin=None, nbndmax=None, analyze_hdecay=True, 
                  ):
        '''
        Convert plane-wave Hamiltonian to atomic orbital basis by plane-wave projection.
        aodata and structure must be loaded previously for this calculation.
        If hgdata is present, then the whole Hamiltonian will be used in the projection. 
        Else if wfndata is present, then use Bloch bands in the projection. 

        Parameters:
        ---------
        savedir:         place where results will be saved
        cutoffs:         Dict[str -> float], cutoff radius for each atomic species, in bohr. This should be a little larger than 
                         the cutoff radius of atomic orbitals in order to account for the nonlocality in the pseudopotential region.
        nbndmin:         minimum band index (1-based), if using Bloch bands in projection
        nbndmax:         maximum band index (1-based), if using Bloch bands in projection
        analyze_hdecay:  whether to analyze the dependence of the Hamiltonian matrix elements on the hopping distance
        '''

        if self.spinful or self.magnetic:
            raise NotImplementedError("Spinful or magnetic calculation is not supported")
        
        if nbndmax is not None:
            assert nbndmax <= self.wfndata.nbnd
            if nbndmin is not None:
                assert nbndmin <= nbndmax
        
        if is_master():
            save_structure_deeph(self.structure, savedir, self.spinful)
        
        if cutoffs is None:
            cutoffs = self.aodata.cutoffs

        pairs = pairs_within_cutoff(self.structure, cutoffs)
        pairs.sort()

        overlaps = None
        if self.hgdata is not None:
            pairs.remove_ji()

            # construct AO Hamiltonian using full PW Hamiltonian
            hoppings = Hpw_to_Hao_HG(self.structure, self.hgdata, self.aodata, pairs, h_or_s='h')
            if self.hgdata.ispaw:
                overlaps = Hpw_to_Hao_HG(self.structure, self.hgdata, self.aodata, pairs, h_or_s='s')
        
        elif self.wfndata is not None:
            # construct AO Hamiltonian using wavefunction projections
            
            if nbndmin is None:
                nbndmin = 1
            if nbndmax is None:
                nbndmax = self.wfndata.nbnd
            
            wfn_proj_atoms = wfn_proj_to_atoms(self.structure, self.aodata, self.wfndata, nbndmin, nbndmax)

            band_shift = 0
            hoppings = Hpw_to_Hao_wfn(self.structure, self.wfndata, self.aodata, pairs, wfn_proj_atoms, nbndmin, nbndmax,
                                      band_shift=band_shift)
            
        else:
            raise ValueError('Must provide either wfndata or hgdata')
        
        if comm is not None:
            comm.Barrier()
        
        if is_master():

            print('\nProjection done, writing output matrices to deeph format')

            save_mat_deeph(savedir, hoppings, 'h')
            
            if overlaps is not None:
                save_mat_deeph(savedir, overlaps, 'o')
            
            if analyze_hdecay:
                analyze_hdecay_deeph(savedir)
        
        if comm is not None:
            comm.Barrier()
    
    
    @mpi_watch
    @simple_timer('\nJob done, total wall time = {t}\n')
    def run_pw2ao_rs(self, savedir, cutoffs=None, analyze_hdecay=True):
        '''
        Convert plane-wave Hamiltonian to atomic orbital basis by integration in real space.

        Parameters:
        ---------
        savedir:         place where result will be saved
        cutoffs:         Dict[str -> float], cutoff radius for each atomic species, in bohr. This parameter is not required. If
                         not provided, then the code will decide which hoppings are nonzero by considering the cutoff of the
                         pseudopotential region and the cutoff of atomic orbitals.
        analyze_hdecay:  whether to analyze the dependence of the Hamiltonian matrix elements on the hopping distance
        '''
        
        if is_master():
            if self.overlaps_only:
                print('\n============================')
                print('Calculating overlap matrices')
                print('============================\n')
                if (comm is not None) and (comm.size > 1):
                    print('WARNING: overlaps_only does not support parallelism yet, please run on only one CPU!\n')
            else:
                print('\n=======================================================')
                print('Reconstructing PW Hamiltonian to AO basis in real space')
                print('=======================================================\n')

        assert self.ecutwfn is not None, 'Must provide cutoff energy ecutwfn'
        assert self.hrdata is not None
        vlocr, Dij, Qij, projR = self.hrdata
        if is_master():
            save_structure_deeph(self.structure, savedir, self.spinful)

        ecut = self.ecutwfn
        basis = self.aodata
        basis.calc_phiQ(ecut * 1.1)
        projR.calc_phiQ(ecut * 1.1)

        # Overlaps
        if is_master(): print('Calculating overlap between basis functions')
        olp_basis = calc_overlap(basis, Ecut=ecut, kind=1)

        if not (self.overlaps_only and Qij is None):
            # skip this step if overlaps_only and using NCPP
            if is_master(): print('\nCalculating overlap between basis and projectors')
            olp_proj_ao = calc_overlap(projR, aodata2=basis, Ecut=ecut, kind=1)

        if Qij is not None:
            if is_master(): print('\nCalculating nonlocal part of overlap matrices')
            dOkb = calc_vkb(olp_proj_ao, Qij)
            overlaps = olp_basis + dOkb
        elif cutoffs is None:
            nloc_pairs = get_nloc_pairs(self.structure, projR.cutoffs, basis.cutoffs)
            dOkb = MatAO.init_mats(nloc_pairs, basis, filling_value=0., dtype='f8')
            overlaps = olp_basis + dOkb
        else:
            overlaps = olp_basis

        if cutoffs is not None:
            pairs_cut = pairs_within_cutoff(self.structure, cutoffs)
            # cutoff overlaps
            overlaps_cut = MatAO.init_mats(pairs_cut, basis, filling_value=0., dtype=self.aomats_dtype)
            overlaps_cut.fillvalue(overlaps)
            overlaps = overlaps_cut

        if self.spinful:
            overlaps.spinless_to_spinful()
        
        if is_master():
            print('\nWriting overlap matrices to disk')
            save_mat_deeph(savedir, overlaps, 'o')
        
        if self.overlaps_only:
            return
        
        # Hamiltonians
        if is_master(): print('\nCalculaing kinetic matrix elements')
        Hkin = calc_overlap(basis, Ecut=ecut, kind=2)
        if self.spinful:
            Hkin.spinless_to_spinful()

        if is_master():
            print('\nConstructing local Kohn-Sham potential under AO basis\n')
        if not self.magnetic:
            worker = GridIntgWorker(self.structure, vlocr.shape, basis)
            out = worker.gridintg(vlocr)
            # make the output pairs of grid integral same as olp_basis
            Hloc = MatAO.init_mats(olp_basis, basis, filling_value=0., dtype=self.aomats_dtype)
            if is_master(): Hloc.fillvalue(out.to_matao())

            if self.spinful:
                Hloc.spinless_to_spinful()

        if is_master():
            print('Calculating nonlocal part of Hamiltonian')
        dHkb = calc_vkb(olp_proj_ao, Dij, self.spinful)
        # print('add')
        hamiltonians = Hkin + Hloc + dHkb

        if cutoffs is not None:
            # cutoff hamiltonians
            hamiltonians_cut = MatAO.init_mats(pairs_cut, basis, filling_value=0., dtype=self.aomats_dtype)
            hamiltonians_cut.fillvalue(hamiltonians)
            hamiltonians = hamiltonians_cut

        if is_master():
            print('\nWriting Hamiltonian matrices to disk')
            save_mat_deeph(savedir, hamiltonians, 'h')

        if comm is not None:
            comm.Barrier()
        
        if is_master() and analyze_hdecay:
            analyze_hdecay_deeph(savedir)



def siesta2deeph(indir, outdir, sysname='siesta', cutoffs=None, upfdir=None, pairs_from_siesta=False, spinful=False):
    # if cutoffs is not provided, then upfdir is needed

    # TODO: move this function elsewhere
    if spinful:
        raise NotImplementedError("Spinful calulation is not supported")

    stru, aodata, hmat, smat = get_hs_siesta(indir, upfdir, sysname=sysname)

    if pairs_from_siesta:
        hamiltonians = hmat.to_matao()
        overlaps = smat.to_matao()
    else:
        # generate connected atom pairs according to HPRO standard
        if cutoffs is None:
            Dij, Qij, projR = read_vnloc(stru, upfdir, interface='qe')
            pairs = pairs_within_cutoff(stru, aodata.cutoffs)
            pairs_nloc = get_nloc_pairs(stru, projR.cutoffs, aodata.cutoffs)
            pairs_all = pairs + pairs_nloc
        else:
            pairs_all = pairs_within_cutoff(stru, cutoffs)
        hamiltonians = MatAO.init_mats(pairs_all, aodata, filling_value=0., dtype='c16' if aodata.spinful else 'f8')
        hamiltonians.fillvalue(hmat.to_matao())
        overlaps = MatAO.init_mats(pairs_all, aodata, filling_value=0., dtype='f8')
        overlaps.fillvalue(smat.to_matao())
    
    save_structure_deeph(stru, outdir, spinful)
    save_mat_deeph(outdir, hamiltonians, 'h')
    save_mat_deeph(outdir, overlaps, 'o')