import numpy as np
from scipy.io import FortranFile

from ..matao.matao import PairsInfo, MatAO
from ..matao.findpairs import pairs_within_cutoff
# from ..v2h.vkb import get_nloc_pairs
from .aodata import AOData
from .struio import from_siesta
from .hrloader import read_vnloc
from .deephio import save_structure_deeph, save_mat_deeph

'''
The main purpose of this module is to read the HSX file generated by SIESTA and convert it to the format supported
by this program.
'''

cs_siesta2wiki = [
    np.array([1.]),
    np.array([-1., 1., -1.]),
    np.array([1., -1., 1., -1., 1.]),
    np.array([-1., 1., -1., 1. -1., 1., -1.])
]

def invert_perm(p):
    s = np.empty_like(p)
    s[p] = np.arange(p.size)
    return s

def get_cs_siesta2wiki(ls_spc):
    orbitals_cs_siesta2wiki = {}
    for spc, orbital_types in ls_spc.items():
        U2wiki = [cs_siesta2wiki[l] for l in orbital_types]
        orbitals_cs_siesta2wiki[spc] = np.concatenate(U2wiki)
    return orbitals_cs_siesta2wiki

def read_orbindx(filename):
    with open(filename) as fp:
        line = fp.readline()
        line_sp = line.split()
        no_u = int(line_sp[0])
        no = int(line_sp[1])
        orb_indx = np.empty((no, 7), dtype='i8') #(io, [ia, iao, isc1, isc2, isc3, iuo, l])
        # meanings of these variables can be found in the end of .ORB_INDX

        for _ in range(2): fp.readline()
        for io in range(no):
            line = fp.readline()
            line_sp = line.split()
            orb_indx[io, :] = list(map(int, (line_sp[1], line_sp[4], line_sp[12], line_sp[13], line_sp[14], line_sp[15], line_sp[6])))
    
    orb_indx[:, 0:2] -= 1; orb_indx[:, 5] -= 1 # 0-based
    
    # sort iao according to l (openmx standard)
    argsort = np.argsort(orb_indx[:, 0]*10 + orb_indx[:, 6], kind='stable')
    tmp = orb_indx[:, 1].copy()
    orb_indx[argsort, 1] = tmp

    assert np.all(orb_indx[:no_u, 5] == np.arange(0, no_u, 1, dtype='i4'))
    tmp = orb_indx[orb_indx[:, 5], 0].copy()
    orb_indx[:, 0] = tmp # make ia in unit cell

    return orb_indx

class siesta_hsx:
    def __init__(self, savedir, sysname='siesta'):
        stru = from_siesta(savedir, sysname=sysname)
        orb_indx = read_orbindx(f'{savedir}/{sysname}.ORB_INDX')
        aodata = AOData(stru, basis_path_root=savedir, aocode='siesta')
        self.stru = stru; self.orb_indx = orb_indx; self.aodata = aodata

        f = FortranFile(f'{savedir}/{sysname}.HSX', 'r')

        self.version = f.read_record('i4')
        assert self.version[0] == 1

        self.is_dp = f.read_record('i4')

        rec = f.read_record('i4')
        self.na_u = rec[0]; self.no_u = rec[1]; self.nspin = rec[2]; self.nspc = rec[3]; self.nsc = rec[4:7]
        # no_u: orbitals in unit cell
        assert self.nspin == 1

        rec = f.read_record('f8')
        ucell = rec[0:9].reshape(3, 3) # bohr
        self.Ef = rec[9]; self.qtot = rec[10]; self.temp = rec[11] # electronic temperature

        # print(np.max(np.abs(ucell-stru.rprim)))

        rec = f.read_record('i4')
        rec = f.read_record('i4')
        for _ in range(self.nspc): f.read_record('i4')

        numh = f.read_record('i4') # (no_u), number of hoppings for each orbital

        # get all connected atom pairs for each orbital in unit cell
        listh = []
        listpairs = []
        for io in range(self.no_u):
            rec = f.read_record('i4') - 1
            assert len(rec) == numh[io]
            translations = orb_indx[rec, 2:5]
            atom_pairs = np.stack((np.full(numh[io], orb_indx[io, 0], dtype='i8'), orb_indx[rec, 0]), axis=1)
            listpairs.append(PairsInfo(stru, translations, atom_pairs))
            listh.append(rec)
        # print(listh)

        indices_uniq = np.unique(np.concatenate([pair.get_indices() for pair in listpairs]))
        pairs_all = PairsInfo.from_indices(stru, indices_uniq)
        pairs_all.sort()
        hmat = MatAO.init_mats(pairs_all, aodata, filling_value=None)
        smat = MatAO.init_mats(pairs_all, aodata, filling_value=None)
        checkmat = MatAO.init_mats(pairs_all, aodata, filling_value=None)

        # sizes: total number of orbitals per atom
        atom_nbrs = stru.atomic_numbers
        sizes = np.empty(stru.natom, 'i4')
        for iat in range(stru.natom):
            sizes[iat] = aodata.norbfull_spc[atom_nbrs[iat]]

        # allocate the concatenated matrix
        hblockptr = np.empty(pairs_all.npairs+1, dtype='i8')
        indtmp = 0
        for ipair in range(pairs_all.npairs):
            hblockptr[ipair] = indtmp
            size1 = sizes[pairs_all.atom_pairs[ipair, 0]]
            size2 = sizes[pairs_all.atom_pairs[ipair, 1]]
            indtmp += size1 * size2
        hblockptr[ipair+1] = indtmp
        hmatcat = np.zeros(indtmp, dtype='f8')
        smatcat = np.zeros(indtmp, dtype='f8')
        icheck = np.zeros(indtmp, dtype='i4')

        for ipair in range(pairs_all.npairs):
            size1 = sizes[pairs_all.atom_pairs[ipair, 0]]
            size2 = sizes[pairs_all.atom_pairs[ipair, 1]]
            hmat.mats[ipair] = hmatcat[hblockptr[ipair]:hblockptr[ipair+1]].reshape(size1, size2)
            smat.mats[ipair] = smatcat[hblockptr[ipair]:hblockptr[ipair+1]].reshape(size1, size2)
            checkmat.mats[ipair] = icheck[hblockptr[ipair]:hblockptr[ipair+1]].reshape(size1, size2)

        # get positions of matrix elements in the concatenated matrix
        listelempos = []
        for io in range(self.no_u):
            pairs = listpairs[io]
            pairindc = pairs_all.findipairs(pairs)
            size2 = sizes[orb_indx[listh[io], 0]]
            iorb1 = orb_indx[io, 1]
            iorb2 = orb_indx[listh[io], 1]
            elempos = hblockptr[pairindc] + iorb1*size2 + iorb2
            icheck[elempos] += 1
            listelempos.append(elempos)
        # print(np.sum(icheck==1), len(icheck))
        assert np.all((icheck==1) + (icheck==0))
        # icheck = None

        # start reading matrices
        for ispin in range(self.nspin):
            for io in range(self.no_u):
                elempos = listelempos[io]
                hmatcat[elempos] = f.read_record('f8') / 2.0 # Ry -> Ha
        
        for io in range(self.no_u):
            elempos = listelempos[io]
            smatcat[elempos] = f.read_record('f8')

        f.close()

        # fix (-1)^m coefficient difference of spharms
        orbs_cs = get_cs_siesta2wiki(aodata.ls_spc)
        for ipair in range(pairs_all.npairs):
            spc1 = atom_nbrs[pairs_all.atom_pairs[ipair, 0]]
            spc2 = atom_nbrs[pairs_all.atom_pairs[ipair, 1]]
            hmat1 = hmat.mats[ipair]
            hmat1[...] = orbs_cs[spc1][:, None] * hmat1 * orbs_cs[spc2][None, :]
            smat1 = smat.mats[ipair]
            smat1[...] = orbs_cs[spc1][:, None] * smat1 * orbs_cs[spc2][None, :]

        self.hmat = hmat
        self.smat = smat
        # print(checkmat.mats[0])

def siesta2deeph(indir, outdir, sysname='siesta', cutoffs=None, upfdir=None, pairs_from_siesta=False):
    raise DeprecationWarning()
    # if cutoffs is not provided, then upfdir is needed

    hsx = siesta_hsx(indir, sysname=sysname)
    
    if pairs_from_siesta:
        hamiltonians = hsx.hmat
        overlaps = hsx.smat
    else:
        # generate connected atom pairs according to HPRO standard
        if cutoffs is None:
            Dij, Qij, projR = read_vnloc(hsx.stru, upfdir, interface='qe')
            pairs = pairs_within_cutoff(hsx.stru, hsx.aodata.cutoffs)
            pairs_nloc = get_nloc_pairs(hsx.stru, projR.cutoffs, hsx.aodata.cutoffs)
            pairs_all = pairs + pairs_nloc
        else:
            pairs_all = pairs_within_cutoff(hsx.stru, cutoffs)
        hamiltonians = MatAO.init_mats(pairs_all, hsx.aodata, filling_value=0., dtype='f8')
        hamiltonians.fillvalue(hsx.hmat)
        overlaps = MatAO.init_mats(pairs_all, hsx.aodata, filling_value=0., dtype='f8')
        overlaps.fillvalue(hsx.smat)
    
    save_structure_deeph(hsx.stru, outdir)
    save_mat_deeph(outdir, hamiltonians, 'h')
    save_mat_deeph(outdir, overlaps, 'o')


